class jab {  
    static encrypt(texto) {
        const tabelaCripto = {
            'a': 'erq',
            'á': 'rtg',
            'à': 'ywr',
            'ã': 'okp',
            'â': 'jnk',
            'ä': 'qpa',
            'b': 'udj',
            'c': 'ibd',
            'ç': 'jmq',
            'd': 'rvf',
            'e': 'pdq',
            'é': 'qfj',
            'ê': 'gdd',
            'ë': 'gho',
            'f': 'fçr',
            'g': 'del',
            'h': 'rfg',
            'i': 'hzn',
            'í': 'ofn',
            'î': 'ihb',
            'ï': 'trd',
            'j': 'fef',
            'k': 'nrç',
            'l': 'qql',
            'm': 'lçp',
            'n': 'kgj',
            'ñ': 'fhv',
            'o': 'bnr',
            'ó': 'alk',
            'ô': 'bot',
            'õ': 'yeg',
            'ö': 'jay',
            'p': 'imk',
            'q': 'hoq',
            'r': 'rnr',
            's': 'aar',
            't': 'ebt',
            'u': 'tet',
            'ú': 'vaz',
            'ü': 'rui',
            'v': 'cjr',
            'w': 'bin',
            'x': 'fle',
            'y': 'gçv',
            'ý': 'sds',
            'z': 'yfu',
            'A': 'thn',
            'Á': 'bts',
            'À': 'alm',
            'Ã': 'ffi',
            'Â': 'saq',
            'Ä': 'lel',
            'B': 'qwe',
            'C': 'cxv',
            'Ç': 'gal',
            'D': 'iol',
            'E': 'awe',
            'É': 'gai',
            'Ê': 'bun',
            'Ë': 'tea',
            'F': 'rth',
            'G': 'vca',
            'H': 'big',
            'I': 'hin',
            'Í': 'asw',
            'Î': 'rfr',
            'Ï': 'iog',
            'J': 'jas',
            'K': 'tep',
            'L': 'dkf',
            'M': 'eqm',
            'N': 'ipa',
            'Ñ': 'çça',
            'O': 'sko',
            'Ó': 'oco',
            'Ô': 'çrf',
            'Õ': 'bko',
            'Ö': 'sku',
            'P': 'çai',
            'Q': 'lin',
            'R': 'gog',
            'S': 'fra',
            'T': 'xol',
            'U': 'zin',
            'Ú': 'drn',
            'Ü': 'din',
            'V': 'kiw',
            'W': 'ing',
            'X': 'mvq',
            'Y': 'mlk',
            'Ý': 'mpk',
            'Z': 'mqç',
            'Ç': 'wqç',
            ',': 'gat',
            '.': 'pli',
            '!': 'pal',
            '?': 'çag',
            ' ': 'wvf',
            '+': 'weç',
            '-': 'bli',
            '=': 'eçq',
            ';': 'sdc',
            ':': 'zwe',
            '@': 'qlp',
            '#': 'ozd',
            '$': 'fzm',
            '%': 'bda',
            '&': 'nqp',
            '*': 'bqw',
            '(': 'dfn',
            ')': 'mvb',
            '[': 'bpl',
            ']': 'nbs',
            '{': 'xql',
            '}': 'lqn',
            '/': 'qls',
            '\\': 'zsa',
            '\'': 'ncs',
            '"': 'poi',
            '~': 'bvn',
            '`': 'qwd',
            '_': 'bve',
            '^': 'mkl',
            '°': 'pof',
            'ª': 'jml',
            '´': 'iun',
            '`': 'bmv',
            '0': 'hks',
            '1': 'rgd',
            '2': 'tyh',
            '3': 'phf',
            '4': 'zfh',
            '5': 'yic',
            '6': 'pay',
            '7': 'sgn',
            '8': 'jfx',
            '9': 'qmx'
        };

        const getRandomCharacter = () => {
            const alfabeto = 'abcdefghijklmnopqrstuvwxyz';
            const indice = Math.floor(Math.random() * alfabeto.length);
            return alfabeto.charAt(indice);
        }
        const troladores = ["zyx",
        "wvu",
        "tsr",
        "qpo",
        "nml",
        "kji",
        "ihg",
        "fed",
        "cba",
        "bca",
        "adc",
        "def",
        "fce",
        "eaf",
        "bda",
        "cfg",
        "ehi",
        "ghj",
        "hij",
        "ija",
        "jkl",
        "lji",
        "mno",
        "nop",
        "opq",
        "pqr",
        "qrs",
        "rst",
        "stu",
        "tuv",
        "uvw",
        "vwx",
        "wxy",
        "xyz",
        "yzx",
        "zxw",
        "wzy",
        "yxz",
        "zwy",
        "wyx",
        "xyw",
        "yxw",
        "wxz",
        "zyw",
        "xwz",
        "zyv",
        "yzv",
        "xuv",
        "yvw",
        "zwu"]
        const adicionarTroll = () => {
            if (Math.random() > 0.85) {
                return troladores[Math.floor(Math.random() * troladores.length)];
            }
            return "";
        };
    
        let textoCripto = 'jab' + getRandomCharacter() + getRandomCharacter() + getRandomCharacter();
        for (let i = 0; i < texto.length; i++) {
            const char = texto.charAt(i);
            textoCripto += tabelaCripto[char] || char;
        }
    
        // Adicionando sequência troladora
        textoCripto += adicionarTroll();
    
        return textoCripto;
    }

    static decrypt(textoCripto) {
        textoCripto = textoCripto.substring(3)
        const tabelaDescripto = {      
                "erq": "a",
                "rtg": "á",
                "ywr": "à",
                "okp": "ã",
                "jnk": "â",
                "qpa": "ä",
                "udj": "b",
                "ibd": "c",
                "jmq": "ç",
                "rvf": "d",
                "pdq": "e",
                "qfj": "é",
                "gdd": "ê",
                "gho": "ë",
                "fçr": "f",
                "del": "g",
                "rfg": "h",
                "hzn": "i",
                "ofn": "í",
                "ihb": "î",
                "trd": "ï",
                "fef": "j",
                "nrç": "k",
                "qql": "l",
                "lçp": "m",
                "kgj": "n",
                "fhv": "ñ",
                "bnr": "o",
                "alk": "ó",
                "bot": "ô",
                "yeg": "õ",
                "jay": "ö",
                "imk": "p",
                "hoq": "q",
                "rnr": "r",
                "aar": "s",
                "ebt": "t",
                "tet": "u",
                "vaz": "ú",
                "rui": "ü",
                "cjr": "v",
                "bin": "w",
                "fle": "x",
                "gçv": "y",
                "sds": "ý",
                "yfu": "z",
                "thn": "A",
                "bts": "Á",
                "alm": "À",
                "ffi": "Ã",
                "saq": "Â",
                "lel": "Ä",
                "qwe": "B",
                "cxv": "C",
                "gal": "Ç",
                "iol": "D",
                "awe": "E",
                "gai": "É",
                "bun": "Ê",
                "tea": "Ë",
                "rth": "F",
                "vca": "G",
                "big": "H",
                "hin": "I",
                "asw": "Í",
                "rfr": "Î",
                "iog": "Ï",
                "jas": "J",
                "tep": "K",
                "dkf": "L",
                "eqm": "M",
                "ipa": "N",
                "çça": "Ñ",
                "sko": "O",
                "oco": "Ó",
                "çrf": "Ô",
                "bko": "Õ",
                "sku": "Ö",
                "çai": "P",
                "lin": "Q",
                "gog": "R",
                "fra": "S",
                "xol": "T",
                "zin": "U",
                "drn": "Ú",
                "din": "Ü",
                "kiw": "V",
                "ing": "W",
                "mvq": "X",
                "mlk": "Y",
                "mpk": "Ý",
                "mqç": "Z",
                "wqç": "Ç",
                "gat": ",",
                "pli": ".",
                "pal": "!",
                "çag": "?",
                "wvf": " ",
                "weç": "+",
                "bli": "-",
                "eçq": "=",
                "sdc": ";",
                "zwe": ":",
                "qlp": "@",
                "ozd": "#",
                "fzm": "$",
                "bda": "%",
                "nqp": "&",
                "bqw": "*",
                "dfn": "(",
                "mvb": ")",
                "bpl": "[",
                "nbs": "]",
                "xql": "{",
                "lqn": "}",
                "qls": "/",
                "zsa": "\\",
                "ncs": "'",
                "poi": "\"",
                "bvn": "~",
                "qwd": "`",
                "bve": "_",
                "mkl": "^",
                "pof": "°",
                "jml": "ª",
                "iun": "´",
                "bmv": "`",
                'hks': '0',
                'rgd': '1',
                'tyh': '2',
                'phf': '3',
                'zfh': '4',
                'yic': '5',
                'pay': '6',
                'sgn': '7',
                'jfx': '8',
                'qmx': '9'
    }; 

        let textoOriginal = '';
        let temp = '';
        for (let i = 3; i < textoCripto.length; i++) {
            temp += textoCripto.charAt(i);
            if (tabelaDescripto[temp] && !["zyx",
            "wvu",
            "tsr",
            "qpo",
            "nml",
            "kji",
            "ihg",
            "fed",
            "cba",
            "bca",
            "adc",
            "def",
            "fce",
            "eaf",
            "bda",
            "cfg",
            "ehi",
            "ghj",
            "hij",
            "ija",
            "jkl",
            "lji",
            "mno",
            "nop",
            "opq",
            "pqr",
            "qrs",
            "rst",
            "stu",
            "tuv",
            "uvw",
            "vwx",
            "wxy",
            "xyz",
            "yzx",
            "zxw",
            "wzy",
            "yxz",
            "zwy",
            "wyx",
            "xyw",
            "yxw",
            "wxz",
            "zyw",
            "xwz",
            "zyv",
            "yzv",
            "xuv",
            "yvw",
            "zwu"].includes(temp)) {
                textoOriginal += tabelaDescripto[temp];
                temp = '';
            }
        }

        return textoOriginal;
    }
}
 
